server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/education
    username: postgres
    password: postgres1
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true
    default-schema: education
elide:
  modelPackage: 'com.besolid.education.model'
  json-api:
    path: /json
    enabled: true
  graphql:
    path: /graphql
    enabled: true
  swagger:
    path: /doc
    enabled: true
    name: 'Education API'
    version: "1.0"
  async:
    enabled: false
    threadPoolSize: 2
    maxRunTime: 65
    cleanupEnabled: true
    queryCleanupDays: 7
    defaultAsyncQueryDAO: true
    export:
      enabled: false
  aggregation-store:
    enabled: true
    default-dialect: h2
    enableMetaDataStore: false
  dynamic-config:
    path: src/main/resources/analytics
    enabled: false
